apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
spec:
  storageClassName: acdh-backup
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: "20Gi"
  volumeMode: Filesystem

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: directus-backup
spec:
  schedule: "20 3 * * *" 
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: directus-backup
            image: quay.io/toolbx-images/alpine-toolbox:3.18
            imagePullPolicy: IfNotPresent
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File  
            volumeMounts:
            - mountPath: /backup
              name: backup           
            - mountPath: /uploads
              name: directus-uploads   
            - mountPath: /extensions
              name: directus-extensions  
              command:
            - /bin/sh
            - -c
            - find /backup -type f -mtime +10 -delete && cd / && tar -czvf /backup/directus-backup-$(date +"%Y_%m_%d_%H_%M").tar.gz uploads extensions  
          volumes:
          - name: backup 
            persistentVolumeClaim:
              claimName: backup
          - name: directus-uploads 
            persistentVolumeClaim:
              claimName: directus-uploads
          - name: directus-extensions
            persistentVolumeClaim:
              claimName: directus-extensions 
          restartPolicy: OnFailure